Trim parsed test fails
MrcJkb/neotest-haskell pull request #33
Opened 2023-01-06 11:14 UTC by Trouble-Truffle

###### Description of changes
### Image preview done with the following commands:
```
nix develop
NVIM_DATA_MINIMAL=$(mktemp -d) nvim -u ./tests/minimal.lua
:cd ~/.local/src/tablefmt
:e ./test/Tests.hs
:lua require'neotest'.setup({adapters = {require('neotest-haskell')}})`
:lua require("neotest").run.run(vim.fn.expand("%"))
#I've no idea why you have to repeat these two lines twice in this order
:lua require'neotest'.setup({adapters = {require('neotest-haskell')}})`
:lua require("neotest").run.run(vim.fn.expand("%"))
```
![image](https://user-images.githubusercontent.com/90542764/210997841-74aa709c-5931-473d-b9dd-c09f719ae037.png)

On personal config:
![image](https://user-images.githubusercontent.com/90542764/210990080-6fad147a-3eb1-4932-a6a3-c96ddf744122.png)

------
the PR removes the `^M`'s
![image](https://user-images.githubusercontent.com/90542764/210996172-87a74d38-8dff-4b33-ac62-f37e68790ca3.png)
![image](https://user-images.githubusercontent.com/90542764/210998012-18fded6d-ddff-4273-a25a-4a9b42e264b9.png)

###### Things done

- [x] Tested, as applicable:
  - [ ] Added plenary specs
  - [x] Manually
- [ ] Updated [CHANGELOG.md](../CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/neotest-haskell/blob/master/CONTRIBUTING.md)

2023-01-06 11:48 UTC, MrcJkb commented
Thanks for the fix, and the detailed description of how to reproduce the bug!

Not sure why you had to run commands twice. Do you need to do that in your regular workflow?

2023-01-06 11:48 UTC, MrcJkb requested changes

2023-01-06 11:48 UTC, MrcJkb commented on lua/neotest-haskell/hspec.lua
> +      error_message = error_message and error_message:gsub('%s*$', '') .. '\n' .. trimmed or trimmed
I would move this fix to the line above:
```lua
local trimmed = line:match('^%s*(.*)'):gsub('%s*$', '')
```
(GitHub won't let me include that line in the review for some reason)

2023-01-06 11:48 UTC, MrcJkb commented on CHANGELOG.md
> +- Trims string ends from failed test results
I will publish a new release when this is merged :smile:  

```suggestion
## [0.2.2] - 2023-01-06
### Fixed
- Trims string ends from failed test results
```

2023-01-06 11:58 UTC, MrcJkb commented on lua/neotest-haskell/hspec.lua
> +      error_message = error_message and error_message:gsub('%s*$', '') .. '\n' .. trimmed or trimmed
Oh wait, `error_message` could be `nil`.
Oh, how I love Lua...

2023-01-06 12:05 UTC, MrcJkb commented on lua/neotest-haskell/hspec.lua
> +      error_message = error_message and error_message:gsub('%s*$', '') .. '\n' .. trimmed or trimmed
Let's do
```lua
local trimmed = (line:match('^%s*(.*)') or line):gsub('%s*$', '')
```
to be safe.

2023-01-06 13:36 UTC, Trouble-Truffle commented
> Thanks for the fix, and the detailed description of how to reproduce the bug!
> 
> Not sure why you had to run commands twice. Do you need to do that in your regular workflow?

Weirdly no, in my config I only have one call to setup

2023-01-06 18:26 UTC, MrcJkb commented
> > Thanks for the fix, and the detailed description of how to reproduce the bug!
> > Not sure why you had to run commands twice. Do you need to do that in your regular workflow?
> 
> Weirdly no, in my config I only have one call to setup

Then I won't treat it as a bug just yet :)
I've updated the minimal config and the troubleshooting guide to hopefully fix it.

2023-01-14 00:43 UTC, merged

2023-01-14 00:43 UTC, MrcJkb commented
I applied my suggestion and merged. @Trouble-Truffle thanks again for the fix!